### ISSUE TITLE
Roundup Issue #1

### ISSUE THREAD

**Issue by SeiferTim** [AxolStudio/STLGameDevRoundUp#1]
To add to the next roundup, use the following format:

```md
{category} short description with [link](/link/to/item)
```

Which should generate the following:

{category} short description with [link](/link/to/item)

**Comment by SeiferTim** [comment]
- [ ] `[core]` this is an item [new test](/new/test)

**Comment by SeiferTim** [comment]
- [ ] `[core]` here is another item [link](/link/to/item)

**Comment by SeiferTim** [comment]
- [ ] `[stuff]` here is another category [link](/link/to/item)

**Comment by SeiferTim** [comment]
{🕹 game update} [Bring It On!](https://bringiton.axolstudio.com/) by [Axol Studio, LLC](https://axolstudio.com/) just had a [major new sticky update ](https://store.steampowered.com/news/app/2020460/view/3877098283553322712?l=english) to the game!

**Comment by SeiferTim** [comment]
{🕹 releases} Fight your way through the North Pole - with Cards in [Yule Duel](https://www.newgrounds.com/portal/view/908342) - a Collectable Card Adventure Game by [Axol Studio, LLC](https://axolstudio.com/)! Free to play on Newgrounds! 🎅

**Comment by SeiferTim** [comment]
{📅events} The next [St Louis Code and Coffee](https://www.meetup.com/code-and-coffee-st-louis/events/297327300/) event is on Sunday, December 17th!

**Comment by SeiferTim** [comment]
{👩‍🏫informative} Some advice on [Choosing the right price for your game](https://www.youtube.com/watch?v=2cHlw2FfS-M)

**Comment by SeiferTim** [comment]
{👩‍🏫informative} [A Postmortem on my 5 year project which flopped pretty hard](https://www.reddit.com/r/gamedev/comments/17p3bgz/a_postmortem_on_my_5_year_project_which_flopped/)

**Comment by SeiferTim** [comment]
{📅events} [Advent of Code 2023](https://adventofcode.com/2023) kicked off on December 1st!

**Comment by SeiferTim** [comment]
{👩‍🏫 informative} Check out this [in-depth breakdown about the game Elite](https://youtu.be/lC4YLMLar5I?si=mELe_hRzdbtd3By0) for the BBC Micro - an entire universe in 22KB!

**Comment by SeiferTim** [comment]
{🕹 releases} A new [Singe](https://kangaroopunch.com/view/ShowSoftware?id=7) release is coming soon from [Kangaroo Punch Studios](https://kangaroopunch.com/)!

**Comment by tsandbrink** [comment]
{devlog} A new devlog update for Campaign Season [https://broskimcdave.itch.io/campaign-season]

**Comment by SeiferTim** [comment]
{📰 articles} Polygon's [Top 50 Games of 2023](https://www.polygon.com/23648669/best-video-games-2023) list. Do you agree?

**Comment by SuperWes** [comment]
{💰classifieds} Pixel Artist Wanted - Hello St. Louis community! I have been working on a casual puzzle golf game for mobile tentatively called 90° Golf and I need a pixel artist to replace the placeholder art I've been using and help solidfy the aesthetic for the game. There's not a lot of art in the game, but I'd like it to be high quality and charmingly animated. If you'd like to learn more please send some samples and your rates to super_wes on Discord, @SuperWes on X, or @superwes.bsky.social on Bluesky.

**Comment by SeiferTim** [comment]
{📰 news} The [Video Game History Foundation](https://gamehistory.org/) [Winter Fundraiser 2023](https://gamehistory.org/donate/) is going on now! Consider supporting the cause!
