### ISSUE TITLE
Some Ideas on things to Implement

### ISSUE THREAD

**Issue by SeiferTim** [AxolStudio/STLGameDevRoundUp#18]
I would like to keep expanding this. Here are a few ideas I had.
Let me know what you think or if you have more suggestions.

- Recurring sections - Add special Issues for things that we want to be on every issue: 
- - Events - a list of all the upcoming events, the RoundUp will pull the next X months worth in each issue
- - Developers - a list of all the local developers and what they do, like individual people or companies and how to reach/find them
- - Classifieds - looking for work or have a job offer, we can add it to a special Issue and it will show up on every Roundup until it is removed
- - Sponsors?

What else could we put in each issue?

**Comment by DrewUniverse** [comment]
+1, would love to see a list of events/devs/classifieds. As for other ideas, I guess it depends on how the newsletter evolves. I might like to see a featured local game each month (rotating). Perhaps there aren't many published titles atm, but that list would grow with time, so eventually you could list a pick-3 or pick-5 once there are enough games in the pool.

**Comment by SeiferTim** [comment]
Yeah I should make a Google Form for people to submit any games they've published from the area just to try and catch 'em all

**Comment by JustinRyanH** [comment]
Blogs/articles written by local developers would be a good addition. It might encourage us to create some localized educational material.

**Comment by SeiferTim** [comment]
I'm going to close this in favor of making a list of things to implement - hopefully that anyone can tackle if they want to contribute!
